### ISSUE TITLE
Test run fails at the end: lint fail with exit code: 1

### ISSUE THREAD

**Issue by Amin-Rehman** [ty0x2333/cocoapods-action#1]
Hello there,

I am sorry if this has been asked before but I just started with gitActions, and it seems all my tests are running just fine but just at the end of the test run I am seeing this failure
```
##[error]lint fail with exit code: 1
```

Can someone help please? I think I have tried every configuration possible but I might be doing something daft.

Thanks, this is what my .yml looks like:

```
name: Swift

on: [push, pull_request]

jobs:
  build:

    runs-on: macOS-latest

    steps:
    - uses: actions/checkout@master
    - name: Switch XCode Version
      run: sudo xcode-select -s /Applications/Xcode_11.app

    - name: Install Dependences
      run: |
        pod repo update
        pod install
      shell: bash

    - name: Test
      uses: ty0x2333/cocoapods-action@master
      with:
        additional_lint_params: --private
        lint: false
        workspace: StubWorkspace.xcworkspace
        scheme: StubWorkspaceTests
        additional_build_params: -destination 'platform=iOS Simulator,name=iPhone 11,OS=13.0'

```

And this is what my output is like.

```
	 Executed 12 tests, with 0 failures (0 unexpected) in 33.134 (33.160) seconds
1709

1710
2019-11-24 15:04:56.393 xcodebuild[1222:14102] [MT] IDETestOperationsObserverDebug: 66.047 elapsed -- Testing started completed.
1711
2019-11-24 15:04:56.393 xcodebuild[1222:14102] [MT] IDETestOperationsObserverDebug: 0.000 sec, +0.000 sec -- start
1712
2019-11-24 15:04:56.393 xcodebuild[1222:14102] [MT] IDETestOperationsObserverDebug: 66.047 sec, +66.047 sec -- end
1713
▸ Test Succeeded
1714
=== Lint ===
1715
pod lib lint --private
1716

1717
[!] Unable to find a podspec in the working directory
1718
##[error]lint fail with exit code: 1
1719
##[error]Node run failed with exit code 1
```

**Comment by oscarito9410** [comment]
Hi, did you find any solution for this issue? I am facing the same issue
Please help @ty0x2333

**Comment by oscarito9410** [comment]
By adding the following configuration the git action deployed successfully.
```
 with:
        workspace: sosmex.xcworkspace
        scheme: sosmexDevelopment
        additional_build_params: -destination 'platform=iOS Simulator,id=761CB82C-2702-47C8-B912-02836EC02359'
        lint: false 
```

Thanks
